export const cuisineList = [
    "Italian",
    "Chinese",
    "Mexican",
    "Indian",
    "Japanese",
    "French",
    "Thai",
    "Greek",
    "Spanish",
    "Mediterranean",
    "Korean",
    "Vietnamese",
    "Turkish",
    "Lebanese",
    "Brazilian",
    "Argentinian",
    "Caribbean",
    "Moroccan",
    "Ethiopian",
    "American",
    "Pizza",
    "Dim Sum",
    "Tacos",
    "Curries",
    "Sushi",
    "Gourmet",
    "Pad Thai",
    "Gyros",
    "Paella",
    "Healthy",
    "Kimchi",
    "Pho",
    "Kebabs",
    "Hummus",
    "BBQ",
    "Asado",
    "Jerk Chicken",
    "Tagine",
    "Injera",
    "Burgers"
];
